### ISSUE TITLE
Error during padding

### ISSUE THREAD

**Issue by AndriiHeonia** [w8r/polygon-offset#11]
Hi, I get this error during the execution:

    Uncaught TypeError: Cannot read property '0' of undefined
        at orientRings (offset.js:2282)
        at Offset.padding (offset.js:2156)

Here is the test code:

    var points = [[116,-94],[116,-84],[123,-84],[123,-94],[116,-94]];
    var padding = (new Offset()).data(points).padding(10);

What I'm doing wrong?

**Comment by w8r** [comment]
This is strange, I will check what is happening. Polygon seems to be valid.

**Comment by mukeshsharma1426** [comment]
This is due to the negative area from the given points. I clipped my points a little bit and then it worked.

**Comment by tvkit** [comment]
The issue can occur in the `orientRings` function when `coordinates[0]` is empty (which is a legitimate condition) or when `coordinates[0][0]` is empty.

```
module.exports.orientRings = function orientRings(coordinates, depth, isHole) {
  ...
  if (isArray(coordinates[0]) && typeof coordinates[0][0] === 'number') {
    ... 
  }
  ...

  if (depth === 0 && typeof coordinates[0][0][0] === 'number') {
    ...
  }

  return coordinates;
};
```

The following checks might help:

```
module.exports.orientRings = function orientRings(coordinates, depth, isHole) {
  ...
  if (isArray(coordinates[0]) && coordinates.length &&  typeof coordinates[0][0] === 'number') {
    ... 
  }
  ...

  if (depth === 0 && coordinates.length && coordinates[0].length && typeof coordinates[0][0][0] === 'number') {
    ...
  }

  return coordinates;
};

```

**Comment by tvkit** [comment]
Related pull request to handle exceptions caused by relatively large padding values: https://github.com/w8r/polygon-offset/pull/15
