### ISSUE TITLE
NPM release of latest code?

### ISSUE THREAD

**Issue by edemaine** [w8r/polygon-offset#42]
The current version on NPM has this code:

```js
module.exports.orientRings = function orientRings(coordinates, depth, isHole) {
  depth = depth || 0;
  var i, len;
  if (isArray(coordinates) && typeof coordinates[0][0] === 'number') {
```

This is missing the nonempty check from the latest code on `master`:

https://github.com/w8r/polygon-offset/blob/ea864563044597daf9811dd76e00bc15caf5bf6b/src/utils.js#L34-L37

Would it be possible to release the current version?  Thanks!

**Comment by w8r** [comment]
done! thank you
