### ISSUE TITLE
Wrong results and undefined behaviours

### ISSUE THREAD

**Issue by Alex-Canales** [w8r/polygon-offset#7]
I compiled the project and used the file ``dist/offset.min.js``.

```javascript
var square = [[1, 1], [1, 2], [2, 2], [2, 1]];  // Square with a side equal to 1
var offset = new Offset();
var marginSquare = offset.data(square).margin(0.3);

var str = "";
for(var i = 0; i < marginSquare[0].length; i++) {
    str += i + " [" + marginSquare[0][i][0] + ", " + marginSquare[0][i][1] + "]\n";
}
console.log(str);
```

The result
```
0 [0.7, 1]
1 [0.7, 2]
2 [0.714683045111454, 2.0451897662151235]
3 [0.714683045111454, 2.0927050983124844]
4 [0.742611856576062, 2.131145809472619]
5 [0.7572949016875158, 2.176335575687742]
6 [0.7957356128476498, 2.2042643871523495]
7 [0.8236644243122581, 2.2427050983124843]
8 [0.8688541905273819, 2.2573881434239382]
9 [0.9072949016875158, 2.285316954888546]
10 [0.9548102337848766, 2.285316954888546]
11 [2, 2.3]
12 [2.0451897662151235, 2.285316954888546]
13 [2.0927050983124844, 2.285316954888546]
14 [2.1311458094726183, 2.2573881434239382]
15 [2.176335575687742, 2.2427050983124843]
16 [2.20426438715235, 2.20426438715235]
17 [2.2427050983124843, 2.176335575687742]
18 [2.2573881434239382, 2.131145809472619]
19 [2.285316954888546, 2.0927050983124844]
20 [2.285316954888546, 2.0451897662151235]
21 [2.3, 2]
22 [2.3, 1]
23 [2.2427050983124843, 0.8236644243122581]
24 [2.0927050983124844, 0.714683045111454]
25 [1.9072949016875158, 0.7146830451114539]
26 [1.757294901687516, 0.8236644243122581]
27 [1.7, 1]
28 [1.7, 1.7]
29 [1.3, 1.7]
30 [1.3, 1]
31 [1.2427050983124843, 0.8236644243122581]
32 [1.0927050983124842, 0.714683045111454]
33 [0.9072949016875158, 0.7146830451114539]
34 [0.7572949016875158, 0.8236644243122581]
35 [0.7, 1]
```
The result looks like that (in red the square, in blue the margin).
![margin bug](https://cloud.githubusercontent.com/assets/12187544/19804627/c1b995c8-9d0f-11e6-985d-448eaba01a64.png)

If I use the padding function, I have this result:

    [[[1, 2.3], [2, 2.3]]]

As you can see, the defined polygon is outside of the square.

I hope those bugs are easy to fix. Your library seems really nice. You should write documentation on public functions, the fact that ``padding`` and ``margin`` functions return multiple arrays was completly unexpected for me.

**Comment by w8r** [comment]
Hi @Alex-Canales 

I updated the dependencies and add the line about linear rings to the docs. You should understand that if you are providing to the library something that can only be understood as line string, it cannot on its own conclude that it's a linear ring, in other words, it doesn't know that it's a closed polygon and the only way to indicate it is to explicitly repeat the first point, which is a common practice in all the geometry formats. Hence the "sausage"-like output.

As for the lack of documentation - there is enough documentation as to how to run or build the library, as well as the pre-built files.

**Comment by w8r** [comment]
I checked your case with properly formatted data
```js
[[1, 1], [1, 2], [2, 2], [2, 1], [1,1]]
```
It works fine

**Comment by Alex-Canales** [comment]
Thank you for the quick replies, it now works like a charm.
