### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by rowanwins** [w8r/polygon-offset#9]
Gday @w8r 

So we've been eyeing off this library as a replacement to jsts in turf. @DenisCarriere ran some performance testing against `jsts` and jsts came out in front by a [fair amount](https://github.com/Turfjs/turf/pull/656) so I've just been doing a bit of digging into the source code to work out what might be going slow.

Checking out the profiles tab in chrome when using `polygon-offset` there appears to be a fair amount of time spent running `union` operations. Digging into the source there are a [few occassions](https://github.com/w8r/polygon-offset/blob/master/src/offset.js#L337-L349) where this sort of thing occurs, if I read it correctly unions get called for every edge of a polygon or line.
````
  if (isArray(this.vertices[0]) && typeof this.vertices[0][0] !== 'number') {
    for (var i = 0, len = this._edges.length; i < len; i++) {
      union = (i === 0) ?
        this.offsetContour(this.vertices[i], this._edges[i]):
        martinez.union(union, this.offsetContour(this.vertices[i], this._edges[i]));
    }
  } else {
    union = (this.vertices.length === 1) ?
      this.offsetPoint() :
      this.offsetContour(this.vertices, this._edges);
  }

  return union;
};
````

This stuck out to me after looking at this [alternate implementation of the martinez algorithm](https://github.com/voidqk/polybooljs) where they provide [this helpful tip for dealing with looping unions](https://github.com/voidqk/polybooljs#advanced-example-1).

I'm wondering if this tip could be applied in this repo? A few changes may need to be made upstream in the `martinez` repo, Im not sure how easy or hard this would be based on the current structure?

Hopefully that makes some amount of sense, happy to help if I can!

Cheers
Rowan

**Comment by w8r** [comment]
That is correct, polygon-offset is built around an awful technique of cascading. To fix that, martinez has to provide certain distinction between holes and contours in the polygons, which is perfectly doable with fixing input format to multipolgons with holes. I really would appreciate some help with implementing that as well

Kind regards,
Alexander Milevski
